// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example usage:
/// ```dart
/// import 'firebase_options.dart';
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  /// Returns the FirebaseOptions for the current platform (Web, Android, iOS, etc.)
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // Select the right configuration based on the platform
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
      // Firebase is not configured for Linux by default
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
      // For any other unsupported platform
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// Configuration for Web platform
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2vzcEoVR5WqL9saHWsqDCpsUss82Y6vU',
    appId: '1:606030319141:web:d34ee9ce7ef9f8656739cc',
    messagingSenderId: '606030319141',
    projectId: 'women-security-app-b668d',
    authDomain: 'women-security-app-b668d.firebaseapp.com',
    storageBucket: 'women-security-app-b668d.firebasestorage.app',
    measurementId: 'G-ZG61SZXWX1',
  );

  /// Configuration for Android platform
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCvk6WkPT-KP3PSm6NE28gS5IaEfiBncI',
    appId: '1:606030319141:android:a7e1f5f822a846ea6739cc',
    messagingSenderId: '606030319141',
    projectId: 'women-security-app-b668d',
    storageBucket: 'women-security-app-b668d.firebasestorage.app',
  );

  /// Configuration for iOS platform
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJmit4M7dqWAG_pkQX7_YBojlvYtUYPoU',
    appId: '1:606030319141:ios:9ae6180a29e744db6739cc',
    messagingSenderId: '606030319141',
    projectId: 'women-security-app-b668d',
    storageBucket: 'women-security-app-b668d.firebasestorage.app',
    androidClientId:
    '606030319141-kl0tnj6kvik1231kcjjmhn3guma7r907.apps.googleusercontent.com',
    iosClientId:
    '606030319141-4d1qr71ni10fhg83bgsnaqk5q3hsmpi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  /// Configuration for macOS platform (same as iOS)
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJmit4M7dqWAG_pkQX7_YBojlvYtUYPoU',
    appId: '1:606030319141:ios:9ae6180a29e744db6739cc',
    messagingSenderId: '606030319141',
    projectId: 'women-security-app-b668d',
    storageBucket: 'women-security-app-b668d.firebasestorage.app',
    androidClientId:
    '606030319141-kl0tnj6kvik1231kcjjmhn3guma7r907.apps.googleusercontent.com',
    iosClientId:
    '606030319141-4d1qr71ni10fhg83bgsnaqk5q3hsmpi3.apps.googleusercontent.com',
    iosBundleId: 'com.example.newApp',
  );

  /// Configuration for Windows platform
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2vzcEoVR5WqL9saHWsqDCpsUss82Y6vU',
    appId: '1:606030319141:web:e389e0bfc301d6d46739cc',
    messagingSenderId: '606030319141',
    projectId: 'women-security-app-b668d',
    authDomain: 'women-security-app-b668d.firebaseapp.com',
    storageBucket: 'women-security-app-b668d.firebasestorage.app',
    measurementId: 'G-V0B3YVNPSH',
  );
}
